# Generated by Django 4.2.5 on 2023-10-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.TextField()),
                ('sex', models.TextField()),
                ('patId', models.TextField()),
                ('history', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
