# Generated by Django 4.2.5 on 2023-10-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_patients_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patid', models.TextField()),
            ],
        ),
    ]
