# Generated by Django 4.2.6 on 2023-12-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_patient_delete_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.TextField()),
                ('ambulance_number', models.TextField()),
                ('area', models.TextField()),
                ('city', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='patAmbulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patId', models.TextField()),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('email', models.TextField()),
                ('sex', models.TextField()),
                ('area', models.TextField()),
                ('city', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='regAmbulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_id', models.TextField()),
                ('name', models.TextField()),
                ('area', models.TextField()),
                ('city', models.TextField()),
                ('current', models.TextField()),
            ],
        ),
    ]
