# Generated by Django 4.2.6 on 2023-12-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_ambulance_patambulance_regambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.TextField()),
                ('ambulance_number', models.TextField()),
                ('number', models.TextField()),
                ('area', models.TextField()),
                ('city', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ambulance',
        ),
    ]
