# Generated by Django 4.2.6 on 2023-12-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_regambulances_delete_regambulance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default=None, max_length=250, null=True, upload_to='media')),
            ],
        ),
    ]
